### ISSUE TITLE
[Coverage]: Add tests for security manager subsystem configuration

### ISSUE THREAD

**Issue by spriadka** [hal/berg#9]
### Description

Currently, we're missing coverage of the securitymanager subsystem configuration (Configuration => Subsystem => Security Manager).
Security Manager subsystem page contains "minimum permissions" and "maximum permissions" vertical navigation items, expecting two spec files to be created
Resources to cover (from `/subsystem=securitymanager:read-resource(recursive=true)`):
- [ ] `/subsystem=security-manager/deployment-permissions=default/minimum-permissions`
- [ ] `/subsystem=security-manager/deployment-permissions=default/minimum-permissions/actions`
- [ ] `/subsystem=security-manager/deployment-permissions=default/minimum-permissions/class`
- [ ] `/subsystem=security-manager/deployment-permissions=default/minimum-permissions/module`
- [ ] `/subsystem=security-manager/deployment-permissions=default/minimum-permissions/name`
- [ ] `/subsystem=security-manager/deployment-permissions=default/maximum-permissions`
- [ ] `/subsystem=security-manager/deployment-permissions=default/maximum-permissions/actions`
- [ ] `/subsystem=security-manager/deployment-permissions=default/maximum-permissions/class`
- [ ] `/subsystem=security-manager/deployment-permissions=default/maximum-permissions/module`
- [ ] `/subsystem=security-manager/deployment-permissions=default/maximum-permissions/name`

You can get inspired by the [tests in the legacy testsuite](https://github.com/hal/testsuite.next/blob/master/tests-configuration-securitymanager/src/test/java/org/jboss/hal/testsuite/test/configuration/security_manager/SecurityManagerTest.java)

### Affects

configuration

### Subsystem

securitymanager

**Comment by OndrejKotek** [comment]
Fixed by #94
